# ===================================
#  Form Behavior Config
# ===================================

name: Form
form: $/saadahsan/formbuilder/models/form/fields.yaml
modelClass: SaadAhsan\CallbackForm\Models\Form

defaultRedirect: saadahsan/formbuilder/forms

create:
    title: Create Form
    redirect: saadahsan/formbuilder/forms/update/:id
    redirectClose: saadahsan/formbuilder/forms

update:
    title: Edit Form
    redirect: saadahsan/formbuilder/forms
    redirectClose: saadahsan/formbuilder/forms

preview:
    title: Preview Form
