# ===================================
#  Relation Behavior Config
# ===================================

fields:
    view:
        list: $/saadahsan/formbuilder/models/formfield/columns.yaml
        toolbarButtons: create|delete
    manage:
        form: $/saadahsan/formbuilder/models/formfield/fields.yaml
        list: $/saadahsan/formbuilder/models/formfield/columns.yaml
