# ===================================
#  Form Behavior Config
# ===================================

name: Callback Submission
form: $/saadahsan/formbuilder/models/submission/fields.yaml
modelClass: SaadAhsan\CallbackForm\Models\Submission

defaultRedirect: saadahsan/formbuilder/submissions

create:
    title: New Submission
    redirect: saadahsan/formbuilder/submissions/update/:id
    redirectClose: saadahsan/formbuilder/submissions

update:
    title: Edit Submission
    redirect: saadahsan/formbuilder/submissions
    redirectClose: saadahsan/formbuilder/submissions

preview:
    title: View Submission
